INSERT INTO `articles` (`id`, `content`, `created_at`, `description`, `status`, `thumbnail_url`, `title`, `updated_at`) VALUES
(1, 'Hukum properti adalah bagian dari hukum perdata yang mengatur kepemilikan, pemanfaatan, dan distribusi properti, baik bergerak maupun tidak bergerak. Di Indonesia, hukum properti terutama mengacu pada Kitab Undang-Undang Hukum Perdata (KUH Perdata) dan Undang-Undang Pokok Agraria (UUPA). Melalui hukum properti, pemilik memiliki hak yang sah untuk menguasai, menggunakan, dan mengalihkan propertinya kepada pihak lain. Regulasi ini mencakup hal-hal seperti jual beli tanah, warisan, sewa-menyewa, hak pakai, hingga sengketa batas tanah.\nDengan adanya hukum properti, diharapkan pemilik dapat mempertahankan hak atas properti yang dimilikinya dan terhindar dari konflik dengan pihak lain. Hukum ini juga memberikan landasan bagi pemerintah untuk melakukan pengaturan penggunaan lahan demi kepentingan umum, seperti pembebasan lahan untuk pembangunan infrastruktur. Namun, kompleksitas regulasi dan birokrasi sering kali membuat masyarakat bingung dan rentan terhadap konflik hukum, khususnya terkait hak kepemilikan dan perubahan status lahan. Maka, pemahaman yang baik mengenai hukum properti menjadi penting untuk melindungi hak-hak kepemilikan serta memastikan pemanfaatan properti sesuai peraturan yang berlaku.', '2025-01-06 21:35:52.470688', 'Hukum properti adalah cabang hukum yang mengatur hak kepemilikan dan penggunaan properti, termasuk tanah dan bangunan. Tujuan utama dari hukum ini adalah melindungi hak pemilik properti dan mencegah terjadinya konflik antar pihak terkait kepemilikan atau pemanfaatan properti. Di Indonesia, hukum properti diatur melalui KUH Perdata dan UUPA, yang memberikan dasar hukum bagi transaksi properti, warisan, dan penyelesaian sengketa tanah.', 'publish', 'https://images.unsplash.com/photo-1528747008803-f9f5cc8f1a64?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', 'Melindungi Hak Kepemilikan dan Pemanfaatan', NULL),
(2, 'Hukum perbankan di Indonesia berfungsi sebagai landasan bagi operasional bank dan lembaga keuangan lainnya. Undang-Undang Nomor 10 Tahun 1998 tentang Perbankan merupakan regulasi utama yang mengatur berbagai aspek, mulai dari pendirian bank, tata kelola, hingga perlindungan nasabah. Dalam konteks ini, hukum perbankan tidak hanya bertujuan untuk menjaga stabilitas sistem keuangan, tetapi juga untuk melindungi hak-hak nasabah serta memastikan transparansi dalam transaksi keuangan.\nPerkembangan teknologi informasi dan komunikasi, seperti kehadiran layanan financial technology (fintech), telah membawa tantangan baru bagi hukum perbankan. Misalnya, perlindungan data nasabah dan keadilan dalam akses layanan keuangan menjadi isu penting yang perlu diatur lebih lanjut.\nPemerintah dan otoritas terkait terus berupaya untuk memperbarui dan menyesuaikan regulasi agar dapat menciptakan iklim perbankan yang sehat dan mendukung pertumbuhan ekonomi nasional. Dengan demikian, hukum perbankan di Indonesia diharapkan mampu beradaptasi dengan perubahan yang cepat dan tetap relevan dalam menghadapi tantangan masa depan.', '2025-01-06 21:35:52.475129', 'Hukum perbankan di Indonesia mengatur operasional bank dan lembaga keuangan lainnya, dengan tujuan menjaga stabilitas sistem keuangan dan melindungi hak-hak nasabah. Berdasarkan Undang-Undang Nomor 10 Tahun 1998 tentang Perbankan, regulasi ini mencakup berbagai aspek mulai dari pendirian bank hingga tata kelola dan transparansi transaksi. Dengan perkembangan teknologi finansial, hukum perbankan juga harus menghadapi tantangan baru, seperti perlindungan data nasabah. Upaya pemerintah dan otoritas terkait dalam memperbarui regulasi diharapkan dapat menciptakan iklim perbankan yang sehat, aman, dan mendukung pertumbuhan ekonomi nasional.', 'publish', 'https://images.unsplash.com/photo-1607863680198-23d4b2565df0?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', 'Hukum Perbankan di Indonesia: Dasar dan Perkembangannya', NULL),
(3, 'Transaksi perbankan yang melibatkan properti, seperti kredit pemilikan rumah (KPR) atau kredit modal usaha dengan jaminan properti, memerlukan perlindungan hukum yang kuat agar hak pemilik properti tetap terjaga. Dalam hal ini, bank bertindak sebagai pihak yang memberikan pembiayaan, sementara properti menjadi jaminan yang dapat diambil alih jika debitur gagal memenuhi kewajibannya.\nSalah satu landasan hukum utama dalam transaksi ini adalah Undang-Undang Nomor 4 Tahun 1996 tentang Hak Tanggungan atas Tanah Beserta Benda-benda yang Berkaitan dengan Tanah di Indonesia. Hak Tanggungan adalah hak jaminan yang diberikan kepada bank atas tanah atau bangunan milik debitur. Proses pendaftaran Hak Tanggungan ini melibatkan notaris dan pejabat pembuat akta tanah (PPAT), yang bertujuan agar hak kepemilikan debitur tercatat secara sah dan aman.\nPentingnya perlindungan hukum ini adalah untuk memberikan kepastian bagi pemilik properti bahwa aset mereka tidak akan disalahgunakan. Selain itu, hak tanggungan juga memungkinkan bank untuk memiliki hak penjaminan yang kuat tanpa melanggar hak-hak pemilik. Jika terjadi wanprestasi, bank dapat melakukan eksekusi hak tanggungan secara sah, misalnya melalui lelang, yang disaksikan oleh otoritas terkait untuk memastikan proses yang transparan dan sesuai aturan.\nDi sisi lain, pemilik properti juga memiliki perlindungan hak untuk mendapatkan informasi yang jelas terkait prosedur dan risiko yang terkait dengan penggunaan properti sebagai jaminan. Ketika informasi ini disampaikan dengan transparan, diharapkan dapat meminimalkan kesalahpahaman antara bank dan nasabah.\nDengan adanya perlindungan hukum yang baik, transaksi perbankan yang melibatkan properti dapat memberikan keamanan bagi kedua belah pihak, baik bagi bank sebagai pemberi pinjaman maupun bagi pemilik properti sebagai peminjam. Perlindungan ini penting agar semua proses transaksi tetap adil, transparan, dan dapat meningkatkan kepercayaan publik terhadap sistem hukum dan perbankan di Indonesia.', '2025-01-06 21:35:52.478128', 'Artikel ini membahas pentingnya perlindungan hukum bagi pemilik properti dalam transaksi perbankan, termasuk dalam pembiayaan properti dan hak kepemilikan. Adanya perlindungan ini penting untuk menjamin keamanan bagi semua pihak dalam transaksi, terutama bagi pemilik properti dan pihak bank yang terlibat.', 'publish', 'https://images.unsplash.com/photo-1501167786227-4cba60f6d58f?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTZ8fGJhbmt8ZW58MHx8MHx8fDA%3D', 'Perlindungan Hukum atas Hak Properti dalam Transaksi Perbankan', NULL),
(4, 'Di era modern ini, kebutuhan akan layanan hukum yang cepat, transparan, dan mudah diakses semakin mendesak. Banyak perusahaan hukum menghadapi tuntutan dari masyarakat yang berharap proses hukum tidak lagi berbelit-belit dan memakan waktu. Hal ini penting karena masyarakat sering kali mengalami kesulitan dalam mengakses layanan hukum akibat hambatan biaya, waktu, dan kerumitan proses yang panjang.\n    \n    Salah satu solusi yang dapat diambil oleh perusahaan hukum adalah dengan memanfaatkan teknologi. Digitalisasi proses hukum, seperti konsultasi online, pembuatan dokumen otomatis, serta sistem manajemen kasus yang terintegrasi, dapat memangkas waktu dan biaya. Perusahaan hukum yang menerapkan sistem ini dapat lebih responsif terhadap kebutuhan klien serta membantu mengurangi beban birokrasi.\n    \n    Selain itu, ada kebutuhan untuk meningkatkan kesadaran hukum di kalangan masyarakat. Perusahaan hukum dapat memberikan edukasi tentang hak-hak hukum dan prosedur yang ada, baik melalui seminar, media sosial, atau konten digital lainnya. Dengan pendekatan ini, masyarakat dapat lebih percaya diri dalam menavigasi sistem hukum dan mengambil keputusan yang tepat.\n    \n    Namun, di balik upaya ini, perusahaan hukum juga harus memastikan bahwa layanan hukum yang diberikan tetap adil dan tidak diskriminatif. Meningkatkan aksesibilitas dan efisiensi dalam layanan hukum tidak hanya akan membantu perusahaan meraih kepercayaan klien, tetapi juga akan berkontribusi dalam menciptakan sistem hukum yang lebih inklusif dan adil bagi semua kalangan.\n    \n    Dengan inovasi yang tepat dan pendekatan yang inklusif, perusahaan hukum dapat berperan besar dalam membangun kepercayaan publik terhadap sistem hukum, serta memastikan bahwa hukum tidak hanya tajam ke bawah, tetapi juga memberikan keadilan bagi seluruh lapisan masyarakat.', '2025-01-06 21:35:52.479634', 'Artikel ini membahas pentingnya peran perusahaan hukum dalam memperbaiki akses dan efisiensi layanan hukum bagi masyarakat. Dengan menghadapi tantangan seperti proses hukum yang panjang dan birokrasi yang rumit, perusahaan hukum harus mengadopsi teknologi dan pendekatan yang lebih inklusif untuk meningkatkan layanan hukum dan kepercayaan masyarakat.', 'publish', 'https://plus.unsplash.com/premium_photo-1698084059560-9a53de7b816b?q=80&w=2011&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', 'Meningkatkan Akses dan Efisiensi Layanan Hukum di Indonesia', NULL)
ON DUPLICATE KEY UPDATE
`updated_at` = VALUES(`updated_at`),
`description` = VALUES(`description`),
`content` = VALUES(`content`),
`title` = VALUES(`title`),
`thumbnail_url` = VALUES(`thumbnail_url`);

INSERT INTO `categories` (`id`, `name`) VALUES
(1, 'Properti'),
(2, 'Bank'),
(3, 'Perusahaan'),
(4, 'Sosial')
ON DUPLICATE KEY UPDATE `name` = VALUES(`name`);

INSERT INTO `article_category` (`article_id`, `category_id`) VALUES
(1, 1),
(2, 2),
(3, 2),
(4, 3),
(4, 4)
ON DUPLICATE KEY UPDATE `article_id` = VALUES(`article_id`), category_id = VALUES(`category_id`);

INSERT INTO thread (id, author, content, created_at, title)
VALUES
    (1, 'Rudi Santoso', 'Pemrograman Java memungkinkan kita untuk membangun aplikasi yang efisien dan skalabel. Salah satu konsep penting dalam Java adalah Object-Oriented Programming (OOP), yang memudahkan pengorganisasian kode dan pemeliharaan aplikasi.', '2025-01-06 10:00:00', 'Pengenalan Pemrograman Java'),
    (2, 'Siti Nurhaliza', 'Spring Framework adalah salah satu framework Java yang sangat populer. Dengan Spring, kita bisa mengembangkan aplikasi berbasis Java dengan lebih cepat dan mudah menggunakan berbagai modul seperti Spring Boot, Spring MVC, dan Spring Data JPA.', '2025-01-06 11:00:00', 'Pengenalan Spring Framework'),
    (3, 'Budi Pratama', 'Spring Boot memudahkan pengembangan aplikasi dengan menyederhanakan konfigurasi dan setup proyek. Kita dapat membuat aplikasi microservices dengan Spring Boot hanya dalam beberapa langkah sederhana.', '2025-01-06 12:00:00', 'Mengenal Spring Boot'),
    (4, 'Andi Wijaya', 'Java Streams adalah fitur baru dalam Java 8 yang memungkinkan kita untuk memproses data dalam bentuk aliran (streams). Dengan Streams, kita dapat memfilter, mengurutkan, dan mengoperasikan data secara deklaratif dengan menggunakan lambda expressions.', '2025-01-06 13:00:00', 'Menggunakan Java Streams'),
    (5, 'Cindy Lestari', 'Spring Security adalah modul dalam Spring Framework yang digunakan untuk menangani keamanan aplikasi. Dengan Spring Security, kita dapat mengimplementasikan autentikasi dan otorisasi dengan mudah menggunakan konfigurasi berbasis Java atau XML.', '2025-01-06 14:00:00', 'Pengenalan Spring Security')
ON DUPLICATE KEY UPDATE
                     id = VALUES(id),
                     author = VALUES(author),
                     content = VALUES(content),
                     created_at = VALUES(created_at),
                     title = VALUES(title);

INSERT INTO thread (id, author, content, created_at, title)
VALUES
    (1, 'Rudi Santoso', 'Pemrograman Java memungkinkan kita untuk membangun aplikasi yang efisien dan skalabel. Salah satu konsep penting dalam Java adalah Object-Oriented Programming (OOP), yang memudahkan pengorganisasian kode dan pemeliharaan aplikasi.', '2025-01-06 10:00:00', 'Pengenalan Pemrograman Java'),
    (2, 'Siti Nurhaliza', 'Spring Framework adalah salah satu framework Java yang sangat populer. Dengan Spring, kita bisa mengembangkan aplikasi berbasis Java dengan lebih cepat dan mudah menggunakan berbagai modul seperti Spring Boot, Spring MVC, dan Spring Data JPA.', '2025-01-06 11:00:00', 'Pengenalan Spring Framework'),
    (3, 'Budi Pratama', 'Spring Boot memudahkan pengembangan aplikasi dengan menyederhanakan konfigurasi dan setup proyek. Kita dapat membuat aplikasi microservices dengan Spring Boot hanya dalam beberapa langkah sederhana.', '2025-01-06 12:00:00', 'Mengenal Spring Boot'),
    (4, 'Andi Wijaya', 'Java Streams adalah fitur baru dalam Java 8 yang memungkinkan kita untuk memproses data dalam bentuk aliran (streams). Dengan Streams, kita dapat memfilter, mengurutkan, dan mengoperasikan data secara deklaratif dengan menggunakan lambda expressions.', '2025-01-06 13:00:00', 'Menggunakan Java Streams'),
    (5, 'Cindy Lestari', 'Spring Security adalah modul dalam Spring Framework yang digunakan untuk menangani keamanan aplikasi. Dengan Spring Security, kita dapat mengimplementasikan autentikasi dan otorisasi dengan mudah menggunakan konfigurasi berbasis Java atau XML.', '2025-01-06 14:00:00', 'Pengenalan Spring Security')
ON DUPLICATE KEY UPDATE
                     id = VALUES(id),
                     author = VALUES(author),
                     content = VALUES(content),
                     created_at = VALUES(created_at),
                     title = VALUES(title);

INSERT INTO comment (id, author, content, created_at, thread_id)
VALUES
    (1, 'Ali Rahman', 'Pemrograman Java memang sangat kuat, terutama dengan konsep OOP-nya. Penerapannya dalam aplikasi besar sangat membantu dalam hal skalabilitas dan pemeliharaan.', '2025-01-06 10:30:00', 1),
    (2, 'Siti Nurhaliza', 'Saya setuju, dengan Spring Boot kita bisa langsung memulai aplikasi tanpa harus memikirkan konfigurasi yang rumit. Spring Boot memang sangat memudahkan pengembangan.', '2025-01-06 11:15:00', 2),
    (3, 'Budi Pratama', 'Spring Boot benar-benar menghemat banyak waktu dalam pengembangan aplikasi, terlebih dengan kemudahan membuat aplikasi berbasis microservices yang scalable.', '2025-01-06 12:10:00', 3),
    (4, 'Rudi Santoso', 'Java Streams sangat membantu dalam memproses data koleksi secara efisien. Dengan Streams, kode menjadi lebih ringkas dan lebih mudah dibaca.', '2025-01-06 13:30:00', 4),
    (5, 'Cindy Lestari', 'Spring Security adalah salah satu modul yang wajib dipahami jika kita ingin membuat aplikasi yang aman. Dengan Spring Security, kita bisa lebih mudah menangani otorisasi dan autentikasi pengguna.', '2025-01-06 14:20:00', 5),
    (6, 'Andi Wijaya', 'Untuk mengamankan aplikasi, penting juga untuk memahami mekanisme token JWT yang dapat digunakan bersama dengan Spring Security.', '2025-01-06 15:00:00', 5),
    (7, 'Ali Rahman', 'Penting untuk selalu mengikuti perkembangan terbaru dari Spring Boot, karena framework ini selalu diperbarui dengan fitur-fitur baru yang sangat berguna.', '2025-01-06 15:30:00', 2),
    (8, 'Budi Pratama', 'Saya sangat suka dengan kemudahan menggunakan Java Streams untuk memanipulasi data tanpa mengubah struktur data aslinya.', '2025-01-06 16:00:00', 4)
ON DUPLICATE KEY UPDATE
                     id = VALUES(id),
                     author = VALUES(author),
                     content = VALUES(content),
                     created_at = VALUES(created_at),
                     thread_id = VALUES(thread_id);
